package jp.co.vermore.mapper;

import java.util.List;

import jp.co.vermore.entity.UsefulMessage;
import jp.co.vermore.entity.UsefulMessageDetail;
import jp.co.vermore.entity.UsefulMessageDetailExample;
import org.apache.ibatis.annotations.Param;

public interface UsefulMessageDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useful_message_detail
     *
     * @mbggenerated
     */
    int countByExample(UsefulMessageDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useful_message_detail
     *
     * @mbggenerated
     */
    int deleteByExample(UsefulMessageDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useful_message_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useful_message_detail
     *
     * @mbggenerated
     */
    int insert(UsefulMessageDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useful_message_detail
     *
     * @mbggenerated
     */
    int insertSelective(UsefulMessageDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useful_message_detail
     *
     * @mbggenerated
     */
    List<UsefulMessageDetail> selectByExampleWithBLOBs(UsefulMessageDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useful_message_detail
     *
     * @mbggenerated
     */
    List<UsefulMessageDetail> selectByExample(UsefulMessageDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useful_message_detail
     *
     * @mbggenerated
     */
    UsefulMessageDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useful_message_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UsefulMessageDetail record, @Param("example") UsefulMessageDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useful_message_detail
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") UsefulMessageDetail record, @Param("example") UsefulMessageDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useful_message_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UsefulMessageDetail record, @Param("example") UsefulMessageDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useful_message_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UsefulMessageDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useful_message_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(UsefulMessageDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useful_message_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UsefulMessageDetail record);
    int insertDetailUsefulMessage(UsefulMessageDetail usefulMessageDetail);

    int deleteDetailUsefulMessage(UsefulMessageDetail usefulMessageDetail);

    int updateDetailUsefulMessage(UsefulMessageDetail usefulMessageDetail);

    String getUsefulMessageDetail(long id);

    List<UsefulMessageDetail> getUsefulMessageDetailAll(Long id);

    UsefulMessage getStudioUsefulMessageDetail(Long id);
}