package jp.co.vermore.entity;

import java.util.Date;

public class UsefulMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useful_message.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useful_message.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useful_message.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useful_message.type
     *
     * @mbggenerated
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useful_message.title
     *
     * @mbggenerated
     */
    private String title;
    private Integer entryType;

    public Integer getEntryType() {
        return entryType;
    }

    public void setEntryType(Integer entryType) {
        this.entryType = entryType;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useful_message.sort_score
     *
     * @mbggenerated
     */
    private Integer sortScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useful_message.excerpt
     *
     * @mbggenerated
     */
    private String excerpt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useful_message.publish_start
     *
     * @mbggenerated
     */
    private Date publishStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useful_message.publish_end
     *
     * @mbggenerated
     */
    private Date publishEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useful_message.create_datetime
     *
     * @mbggenerated
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useful_message.update_datetime
     *
     * @mbggenerated
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useful_message.del_flg
     *
     * @mbggenerated
     */
    private Boolean delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useful_message.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useful_message.id
     *
     * @return the value of useful_message.id
     * @return the value of useful_message.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useful_message.id
     *
     * @param id the value for useful_message.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useful_message.uuid
     *
     * @return the value of useful_message.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useful_message.uuid
     *
     * @param uuid the value for useful_message.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useful_message.date
     *
     * @return the value of useful_message.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useful_message.date
     *
     * @param date the value for useful_message.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useful_message.type
     *
     * @return the value of useful_message.type
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useful_message.type
     *
     * @param type the value for useful_message.type
     *
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useful_message.title
     *
     * @return the value of useful_message.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useful_message.title
     *
     * @param title the value for useful_message.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useful_message.sort_score
     *
     * @return the value of useful_message.sort_score
     *
     * @mbggenerated
     */
    public Integer getSortScore() {
        return sortScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useful_message.sort_score
     *
     * @param sortScore the value for useful_message.sort_score
     *
     * @mbggenerated
     */
    public void setSortScore(Integer sortScore) {
        this.sortScore = sortScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useful_message.excerpt
     *
     * @return the value of useful_message.excerpt
     *
     * @mbggenerated
     */
    public String getExcerpt() {
        return excerpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useful_message.excerpt
     *
     * @param excerpt the value for useful_message.excerpt
     *
     * @mbggenerated
     */
    public void setExcerpt(String excerpt) {
        this.excerpt = excerpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useful_message.publish_start
     *
     * @return the value of useful_message.publish_start
     *
     * @mbggenerated
     */
    public Date getPublishStart() {
        return publishStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useful_message.publish_start
     *
     * @param publishStart the value for useful_message.publish_start
     *
     * @mbggenerated
     */
    public void setPublishStart(Date publishStart) {
        this.publishStart = publishStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useful_message.publish_end
     *
     * @return the value of useful_message.publish_end
     *
     * @mbggenerated
     */
    public Date getPublishEnd() {
        return publishEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useful_message.publish_end
     *
     * @param publishEnd the value for useful_message.publish_end
     *
     * @mbggenerated
     */
    public void setPublishEnd(Date publishEnd) {
        this.publishEnd = publishEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useful_message.create_datetime
     *
     * @return the value of useful_message.create_datetime
     *
     * @mbggenerated
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useful_message.create_datetime
     *
     * @param createDatetime the value for useful_message.create_datetime
     *
     * @mbggenerated
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useful_message.update_datetime
     *
     * @return the value of useful_message.update_datetime
     *
     * @mbggenerated
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useful_message.update_datetime
     *
     * @param updateDatetime the value for useful_message.update_datetime
     *
     * @mbggenerated
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useful_message.del_flg
     *
     * @return the value of useful_message.del_flg
     *
     * @mbggenerated
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useful_message.del_flg
     *
     * @param delFlg the value for useful_message.del_flg
     *
     * @mbggenerated
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useful_message.note
     *
     * @return the value of useful_message.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useful_message.note
     *
     * @param note the value for useful_message.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note;
    }
}